### ISSUE TITLE
切歌时崩溃

### ISSUE THREAD

**Issue by ColdLemonTea** [Moriafly/SaltPlayerSource#1124]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Xiaomi 15 (dada)

### 系统版本 System Version

HyperOS 2.0.26.11 Android 15

### 软件版本 App Version

10.8.0-alpha01

### 描述问题 Describe issue

如题，切歌时软件崩溃

**Comment by GaodaGG** [comment]
一样问题，log如下
```
FATAL EXCEPTION: DefaultDispatcher-worker-14 (Ask Gemini)
                                                                                                    Process: com.salt.music, PID: 19638
                                                                                                    java.lang.IllegalStateException: Cannot invoke setValue on a background thread
                                                                                                    	at androidx.core.dr0.Ϳ(SourceFile:35)
                                                                                                    	at androidx.core.lh1.Ԯ(SourceFile:3)
                                                                                                    	at androidx.core.ழ.invoke(SourceFile:113)
                                                                                                    	at androidx.core.zv0.Ϳ(SourceFile:13)
                                                                                                    	at androidx.core.xv0.invokeSuspend(SourceFile:169)
                                                                                                    	at androidx.core.ࡃ.resumeWith(SourceFile:9)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:61)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4c6d58, Dispatchers.Default]
```
