### ISSUE TITLE
闪退，无法接受条款

### ISSUE THREAD

**Issue by KingRootwang** [Moriafly/SaltPlayerSource#487]
#### 基本信息 The basic information

软件版本 Software version：`8.3.0-build2023011201`
系统版本 System version：`Android 13`

#### 反馈内容 Content of the feedback

同意或拒绝都会闪退

![Screenshot_20230112-114244_椒盐音乐](https://user-images.githubusercontent.com/76800400/211979621-18e937e6-e6ad-4c80-b16d-b47d18680496.png)

——————
[Device Brand]: OnePlus
[Device Model]: GM1910
[Display]: TQ1A.230105.002
[Android Version]: 13
[API Version]: 33
[System Locale]: zh_CN
[Package Name]: com.salt.music
[Error Type]: Jvm
[Crash Time]: 2023-01-12T11:48:07.071
[Stack Trace]:
android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1982)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by KingRootwang** [comment]
对了在 `8.2.5-build-2022122103` 是正常的

**Comment by Moriafly** [comment]
尝试更新 8.3.0-build2023011202

**Comment by KingRootwang** [comment]
> 尝试更新 8.3.0-build2023011202

可以了诶，好快！！

**Comment by yeyunHZ** [comment]
你好，我的app也遇到这个问题了，无法找到复现场景，请问能告诉我是怎么修复的吗
