### ISSUE TITLE
播放时突然崩溃

### ISSUE THREAD

**Issue by Simlalsy** [Moriafly/SaltPlayerSource#617]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：2023072601
系统版本 System 

> 

> version：MIUI14.0.23.7.24开发版

#### 反馈内容 Content of the feedback

播放时突然崩溃，通知仍在，显示播放状态，但是无声音输出，进度条也不走，该问题从去年直到现在，这个版本仍有，由于触发条件未知，随机性较大，也没怎么反馈 
以下内容是日志：

================================================================
    Generated by AppErrorsTracking
    Project Url: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 27655
[CPU ABI]: arm64-v8a
[Package Name]: com.salt.music
[Version Name]: 8.13.1
[Version Code]: 2023072601
[Error Type]: JVM
[Crash Time]: 2023-07-28T22:02:08.105
[Stack Trace]:
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5504d1 u0 com.salt.music/.service.MusicService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2100)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2071)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by Moriafly** [comment]
尝试更新 10.9.0-alpha04
