### ISSUE TITLE
挂在后台长时间不用，重新返回，播放时闪退

### ISSUE THREAD

**Issue by Simlalsy** [Moriafly/SaltPlayerSource#927]
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: UP1A.231005.007
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 5075
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.salt.music
[Version Name]: 10.5.0-beta01
[Version Code]: 2024080601
[Target SDK]: 34
[Min SDK]: 23
[Error Type]: JVM
[Crash Time]: 2024-08-14T13:02:27.166
[Stack Trace]:
java.lang.IndexOutOfBoundsException: Index 6, size 6
	at androidx.core.ey1.Ԩ(SourceFile:27)
	at androidx.core.ey1.ԩ(SourceFile:1)
	at androidx.core.s90.ޱ(SourceFile:5)
	at androidx.core.l11.Ԩ(SourceFile:1)
	at androidx.core.i01.Ϳ(SourceFile:1)
	at androidx.core.q11.Ԩ(SourceFile:23)
	at androidx.core.r11.invoke(SourceFile:64)
	at androidx.core.ঈ.Ԫ(SourceFile:24)
	at androidx.core.ঈ.invoke(SourceFile:193)
	at androidx.core.yw0.Ԩ(SourceFile:74)
	at androidx.core.bn0.ނ(SourceFile:39)
	at androidx.core.bq3.ԩ(SourceFile:1)
	at androidx.core.zv0.ނ(SourceFile:15)
	at androidx.core.ɒ.ԩ(SourceFile:1)
	at androidx.core.zv0.ނ(SourceFile:15)
	at androidx.core.hw.ԩ(SourceFile:99)
	at androidx.core.zv0.ނ(SourceFile:15)
	at androidx.core.pw0.invoke(SourceFile:121)
	at androidx.core.pw0.invoke(SourceFile:105)
	at androidx.core.s41.ރ(SourceFile:114)
	at androidx.core.hv3.Ϳ(SourceFile:48)
	at androidx.core.iv3.Ԫ(SourceFile:140)
	at androidx.core.lc2.Ϳ(SourceFile:1)
	at androidx.core.qw0.ࢧ(SourceFile:115)
	at androidx.core.hw0.ޘ(SourceFile:18)
	at androidx.core.hw0.ޙ(SourceFile:18)
	at androidx.core.kj1.ԩ(SourceFile:8)
	at androidx.core.kj1.ׯ(SourceFile:140)
	at androidx.core.kj1.ՠ(SourceFile:80)
	at androidx.core.ಽ.ކ(SourceFile:34)
	at androidx.core.hc2.Ϳ(SourceFile:4)
	at androidx.core.ಽ.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:24836)
	at android.view.View.updateDisplayListIfDirty(View.java:23619)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
	at android.view.View.updateDisplayListIfDirty(View.java:23544)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:736)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:745)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:855)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5779)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5422)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4502)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3052)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10611)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1247)
	at android.view.Choreographer.doFrame(Choreographer.java:1114)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1731)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1090)

**Comment by Moriafly** [comment]
#925 似乎是一样的

**Comment by Moriafly** [comment]
移动到 #925
