### ISSUE TITLE
崩溃 measure is called on a deactivated node

### ISSUE THREAD

**Issue by Simlalsy** [Moriafly/SaltPlayerSource#939]
播放，挂后台一个半小时，息屏三分钟，重新打开闪退

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: UP1A.231005.007
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 30328
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.salt.music
[Version Name]: 10.5.0-beta03
[Version Code]: 2024081701
[Target SDK]: 34
[Min SDK]: 23
[Error Type]: JVM
[Crash Time]: 2024-08-21T14:36:39.820
[Stack Trace]:
java.lang.IllegalArgumentException: measure is called on a deactivated node
	at androidx.core.gm4.ޕ(SourceFile:3)
	at androidx.core.ul0.ࢤ(SourceFile:211)
	at androidx.core.ul0.ވ(SourceFile:106)
	at androidx.core.wo0.Ԩ(SourceFile:56)
	at androidx.core.xp0.Ԩ(SourceFile:21)
	at androidx.core.yp0.invoke(SourceFile:838)
	at androidx.core.ཤ.invoke(SourceFile:533)
	at androidx.core.bm0.ԩ(SourceFile:74)
	at androidx.core.zc0.ވ(SourceFile:39)
	at androidx.core.j53.Ԫ(SourceFile:1)
	at androidx.core.fl0.ވ(SourceFile:15)
	at androidx.core.đ.Ԫ(SourceFile:1)
	at androidx.core.fl0.ވ(SourceFile:15)
	at androidx.core.cm.Ԫ(SourceFile:99)
	at androidx.core.fl0.ވ(SourceFile:15)
	at androidx.core.ތ.invoke(SourceFile:80)
	at androidx.core.f5.ޟ(SourceFile:114)
	at androidx.core.n93.Ϳ(SourceFile:52)
	at androidx.core.o93.Ԫ(SourceFile:140)
	at androidx.core.rx1.Ϳ(SourceFile:3)
	at androidx.core.ul0.ࢤ(SourceFile:136)
	at androidx.core.ml0.ޘ(SourceFile:18)
	at androidx.core.ml0.ޙ(SourceFile:18)
	at androidx.core.n61.ԩ(SourceFile:8)
	at androidx.core.n61.ׯ(SourceFile:140)
	at androidx.core.n61.ՠ(SourceFile:90)
	at androidx.core.ȷ.ކ(SourceFile:36)
	at androidx.core.ȷ.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:24836)
	at android.view.View.updateDisplayListIfDirty(View.java:23619)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.updateDisplayListIfDirty(View.java:23606)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.updateDisplayListIfDirty(View.java:23606)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.updateDisplayListIfDirty(View.java:23606)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.updateDisplayListIfDirty(View.java:23606)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.updateDisplayListIfDirty(View.java:23606)
	at android.view.View.draw(View.java:24523)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4684)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4441)
	at android.view.View.draw(View.java:24836)
	at com.android.internal.policy.DecorView.draw(DecorView.java:904)
	at android.view.View.updateDisplayListIfDirty(View.java:23619)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:736)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:745)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:855)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5779)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5422)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4502)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3052)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10611)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1247)
	at android.view.Choreographer.doFrame(Choreographer.java:1114)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1731)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1090)

**Comment by Moriafly** [comment]
您好，使用的软件版本是？

**Comment by Moriafly** [comment]
已在 10.6.0 alpha 中修复
